DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swin_admoe
  NAME: swin_admoe_tiny_shifted_patch4_window8_256
  DROP_PATH_RATE: 0.2
  SWIN_ADMOE:
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 8
    MLP_RATIO: 4.0
    QKV_BIAS: True
    APE: False
    PATCH_NORM: True
    PRETRAINED_WINDOW_SIZES: [0, 0, 0, 0]
    SHIFT_MLP_RATIO: 1.0
    IS_PRETRAIN: True
    USE_SHIFTED_LAST_LAYER: True